// src/store/actionTypes.js
export const SET_LEVEL = 'SET_LEVEL';
export const SET_WALLET_BALANCE = 'SET_WALLET_BALANCE';
export const SET_MODAL_VISIBLE = 'SET_MODAL_VISIBLE';
export const SET_SELECTED_COUNTRY = 'SET_SELECTED_COUNTRY';
export const SET_CONTACT_NUMBER = 'SET_CONTACT_NUMBER';
export const SET_PACKAGE_QUANTITY = 'SET_PACKAGE_QUANTITY';
export const SET_PACKAGES = 'SET_PACKAGES';
export const SET_PROFILE = 'SET_PROFILE';
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';
export const SET_PEOPLE_SUGGESTIONS = 'SET_PEOPLE_SUGGESTIONS';
export const SET_CARD_DATA='SET_CARD_DATA'